version: '2'
services:

  dev:
    image: node:latest
    volumes:
      - .:/usr/src/app
      - ~/.aws/:/root/.aws
      - ~/.gcloud/:/root/.gcloud
    working_dir: /usr/src/app
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
    env_file: .env